production in process

diff --git a/Dockerfile.prod b/Dockerfile.prod
--- a/Dockerfile.prod
+++ b/Dockerfile.prod
@@ -1,5 +1,3 @@
-# Dockerfile.prod (production)
-
 # Étape 1 : Construction de l'application dans une image Golang
 FROM golang:1.22 AS BUILDER
 
@@ -23,7 +21,13 @@ FROM ubuntu:22.04
 
 # Installer les dépendances nécessaires
 RUN apt-get update && apt-get install -y \
-    libc6
+    libc6 \
+    wget \
+    && rm -rf /var/lib/apt/lists/*
+
+# Télécharger et installer wait-for-it
+RUN wget -O /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
+    && chmod +x /usr/local/bin/wait-for-it
 
 # Définir le répertoire de travail
 WORKDIR /app
@@ -34,8 +38,11 @@ COPY --from=BUILDER /app/app /app
 # Copier le fichier .env
 COPY .env /app/.env
 
+# Vérifier si le fichier .env existe
+RUN if [ ! -f /app/.env ]; then echo "Warning: .env file not found." && exit 1; fi
+
 # Exposer le port sur lequel l'API écoutera
 EXPOSE 3003
 
-# Démarrer l'application
-CMD ["./app"]
+# Vérification de la présence du binaire et démarrage de l'application
+CMD ["sh", "-c", "if [ -f ./app ]; then ./app; else echo 'App binary not found!' && exit 1; fi"]
